# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loyalty_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
