# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favore', '0002_user_loyalty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
